version: '2.1'

volumes:
  shipping-api-mysql-data:
    driver: local

services:
  # MySQL 5.6
  mysql:
    image: mysql:5.6
    container_name: economy-mysql
    command: --default-authentication-plugin=mysql_native_password # bugfix
    volumes:
      - shipping-api-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=economy
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.3-nginx
    container_name: economy-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
      - "443:8083"
    links:
      - mysql
    environment:
      - XDEBUG_ENABLED=true
      - PHP_IDE_CONFIG=serverName=ambientum
